"""Tool configuration — ReconRanger v4.0"""
from typing import Dict, Any, Optional

VERSION = "4.0"
DESCRIPTION = "ReconRanger v4.0 — Bug Bounty CLI Tool Manager"

TOOL_SCHEMA = {
    "type": str,
    "binary": str,
    "description": str,
}

# 15 categories — no duplicates, no dead entries
CATEGORIES = {
    "core": [
        "bbot", "subfinder", "sublist3r", "subdomainizer", "assetfinder",
        "dnsx", "httpx", "naabu", "katana", "gospider",
        "ffuf", "nuclei", "amass",
    ],
    "subdomains": [
        "shuffledns", "puredns", "github-subdomains",
    ],
    "ports": [
        "nmap", "naabu", "masscan", "metabigor",
    ],
    "fuzzing": [
        "ffuf", "feroxbuster", "gobuster", "dirsearch", "kiterunner",
    ],
    "web": [
        "arjun", "x8", "paramspider", "cewl",
    ],
    "js": [
        "linkfinder", "jsfinder", "jsleak", "jsluice", "jsecret",
    ],
    "secrets": [
        "secretfinder", "gitleaks", "trufflehog", "git-dumper", "githound",
    ],
    "osint": [
        "gau", "waybackurls", "github-dorks", "virustotalx", "jeeves",
    ],
    "vuln": [
        "xsstrike", "dalfox", "sqlmap", "ghauri", "dotdotpwn",
        "graphqlmap", "nosqlmap", "cvinder", "aidor",
        "metasploit-framework", "ssrfmap", "corsy", "jwt_tool",
    ],
    "cloud": [
        "cloud_enum", "s3scanner",
    ],
    "takeover": [
        "subjack", "subzy",
    ],
    "cms": [
        "wpscan", "droopescan", "nikto",
    ],
    "fingerprinting": [
        "wafw00f", "graphw00f", "gowitness", "hakoriginfinder",
    ],
    "automation": [
        "pegpon", "reconftw",
    ],
    "utils": [
        "anew", "gf", "seclists", "interactsh", "uro", "notify", "enumrust",
    ],
}

TOOL_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "bbot": {
        "type": "python", "package": "bbot", "binary": "bbot",
        "description": "All-in-one recon framework: subdomains, ports, endpoints, vulns",
        "example": "bbot -t example.com -m subfinder httpx nuclei",
    },
    "subfinder": {
        "type": "go",
        "package": "github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest",
        "binary": "subfinder",
        "description": "Passive subdomain discovery using 30+ sources",
        "example": "subfinder -d target.com -silent -all -o subs.txt",
    },
    "httpx": {
        "type": "go",
        "package": "github.com/projectdiscovery/httpx/cmd/httpx@latest",
        "binary": "httpx",
        "description": "HTTP probing: status codes, titles, tech detection",
        "example": "cat subs.txt | httpx -silent -status-code -title -tech-detect",
    },
    "dnsx": {
        "type": "go",
        "package": "github.com/projectdiscovery/dnsx/cmd/dnsx@latest",
        "binary": "dnsx",
        "description": "Multi-purpose DNS toolkit for resolution and brute-force",
        "example": "cat subs.txt | dnsx -a -resp -silent",
    },
    "nuclei": {
        "type": "go",
        "package": "github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest",
        "binary": "nuclei",
        "description": "Template-based vulnerability scanner with 9000+ community templates",
        "post_install": "nuclei -update-templates -silent",
        "example": "cat alive.txt | nuclei -t exposures/ -severity critical,high",
    },
    "katana": {
        "type": "go",
        "package": "github.com/projectdiscovery/katana/cmd/katana@latest",
        "binary": "katana",
        "description": "Next-gen crawling framework with JS rendering",
        "example": "katana -u https://target.com -depth 3 -js-crawl -silent",
    },
    "ffuf": {
        "type": "go",
        "package": "github.com/ffuf/ffuf/v2@latest",
        "binary": "ffuf",
        "description": "Fast web fuzzer for directories, files, and parameters",
        "example": "ffuf -w wordlist.txt -u https://target.com/FUZZ",
    },
    "gospider": {
        "type": "go",
        "package": "github.com/jaeles-project/gospider@latest",
        "binary": "gospider",
        "description": "Fast web spider for endpoint and link discovery",
        "example": "gospider -s https://target.com -o output",
    },
    "assetfinder": {
        "type": "go",
        "package": "github.com/tomnomnom/assetfinder@latest",
        "binary": "assetfinder",
        "description": "Find subdomains from Certificate Transparency logs",
        "example": "assetfinder --subs-only target.com",
    },
    "amass": {
        "type": "go",
        "package": "github.com/owasp-amass/amass/v4/cmd/amass@latest",
        "binary": "amass",
        "description": "In-depth attack surface mapping and graph visualization",
        "example": "amass enum -d target.com -o subs.txt",
    },
    "naabu": {
        "type": "go",
        "package": "github.com/projectdiscovery/naabu/v2/cmd/naabu@latest",
        "binary": "naabu",
        "description": "Fast SYN/CONNECT port scanner for recon pipelines",
        "example": "naabu -host target.com -top-ports 1000 -silent",
    },
    "sublist3r": {
        "type": "python", "package": "sublist3r", "binary": "sublist3r",
        "description": "Subdomain enumeration via OSINT: Google, Bing, DNSdumpster",
        "example": "sublist3r -d target.com -o subs.txt",
    },
    "subdomainizer": {
        "type": "git",
        "repo": "https://github.com/nsonaniya2010/SubDomainizer.git",
        "path": "/opt/SubDomainizer", "binary": "subdomainizer",
        "entrypoint": "/opt/SubDomainizer/SubDomainizer.py",
        "requirements": ["-r", "/opt/SubDomainizer/requirements.txt"],
        "description": "Find subdomains and secrets in JS and external resources",
        "example": "subdomainizer -u https://target.com -o results.txt",
    },
    "shuffledns": {
        "type": "go",
        "package": "github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest",
        "binary": "shuffledns",
        "description": "MassDNS wrapper for mass subdomain brute-forcing",
        "example": "shuffledns -list subs.txt -d target.com -r resolvers.txt",
    },
    "puredns": {
        "type": "go",
        "package": "github.com/d3mondev/puredns/v2@latest",
        "binary": "puredns",
        "description": "Reliable subdomain brute-force with wildcard filtering",
        "example": "puredns bruteforce wordlist.txt target.com",
    },
    "github-subdomains": {
        "type": "go",
        "package": "github.com/gwen001/github-subdomains@latest",
        "binary": "github-subdomains",
        "description": "Find subdomains leaked in GitHub commits and repos",
        "example": "github-subdomains -d target.com -t GITHUB_TOKEN",
    },
    "nmap": {
        "type": "apt", "package": "nmap", "binary": "nmap", "apt": "nmap",
        "description": "Industry-standard port scanning and service detection",
        "example": "nmap -sV -sC -p- target.com",
    },
    "masscan": {
        "type": "git",
        "repo": "https://github.com/robertdavidgraham/masscan.git",
        "path": "/opt/masscan", "binary": "masscan",
        "build_cmd": "make -j$(nproc)",
        "description": "Internet-scale port scanner — 65535 ports in minutes",
        "example": "masscan -p1-65535 --rate=10000 target.com",
    },
    "metabigor": {
        "type": "go",
        "package": "github.com/j3ssie/metabigor@latest",
        "binary": "metabigor",
        "description": "ASN lookup, IP range, and CIDR enumeration",
        "example": "metabigor net -d target.com",
    },
    "feroxbuster": {
        "type": "cargo", "package": "feroxbuster", "binary": "feroxbuster",
        "description": "Fast, recursive content discovery written in Rust",
        "example": "feroxbuster -u https://target.com -w wordlist.txt --depth 3",
    },
    "gobuster": {
        "type": "go",
        "package": "github.com/OJ/gobuster/v3@latest",
        "binary": "gobuster",
        "description": "Directory, DNS, and vhost brute-forcing tool",
        "example": "gobuster dir -u https://target.com -w wordlist.txt",
    },
    "dirsearch": {
        "type": "git",
        "repo": "https://github.com/maurosoria/dirsearch.git",
        "path": "/opt/dirsearch", "binary": "dirsearch",
        "entrypoint": "/opt/dirsearch/dirsearch.py",
        "requirements": ["-r", "/opt/dirsearch/requirements.txt"],
        "description": "Web path brute-forcing with threading and recursion",
        "example": "dirsearch -u https://target.com",
    },
    "kiterunner": {
        "type": "git",
        "repo": "https://github.com/assetnote/kiterunner.git",
        "path": "/opt/kiterunner", "binary": "kr",
        "build_cmd": "make build",
        "description": "Context-aware API route discovery using real-world wordlists",
        "example": "kr scan https://target.com -w routes-small.kite",
    },
    "arjun": {
        "type": "python", "package": "arjun", "binary": "arjun",
        "description": "HTTP parameter discovery suite",
        "example": "arjun -u https://target.com",
    },
    "x8": {
        "type": "cargo", "package": "x8", "binary": "x8",
        "description": "Hidden HTTP parameter discovery written in Rust",
        "example": "x8 -u https://target.com/ -w wordlist.txt",
    },
    "paramspider": {
        "type": "python", "package": "paramspider", "binary": "paramspider",
        "description": "Mine parameterised URLs from web archives",
        "example": "paramspider -d target.com",
    },
    "cewl": {
        "type": "apt", "package": "cewl", "binary": "cewl", "apt": "cewl",
        "description": "Custom wordlist generator by spidering a target",
        "example": "cewl -d 2 -m 8 -w custom.txt https://target.com",
    },
    "linkfinder": {
        "type": "git",
        "repo": "https://github.com/GerbenJavado/LinkFinder.git",
        "path": "/opt/LinkFinder", "binary": "linkfinder",
        "entrypoint": "/opt/LinkFinder/linkfinder.py",
        "requirements": ["-r", "/opt/LinkFinder/requirements.txt"],
        "description": "Discover endpoints and parameters in JavaScript files",
        "example": "python3 linkfinder.py -i https://target.com/main.js -o cli",
    },
    "jsfinder": {
        "type": "git",
        "repo": "https://github.com/0x240x23elu/jsfinder.git",
        "path": "/opt/jsfinder", "binary": "jsfinder",
        "entrypoint": "/opt/jsfinder/JSFinder.py",
        "requirements": ["-r", "/opt/jsfinder/requirements.txt"],
        "description": "Extract URLs and subdomains from JavaScript files",
        "example": "python3 JSFinder.py -u https://target.com",
    },
    "jsleak": {
        "type": "go",
        "package": "github.com/channyein1337/jsleak@latest",
        "binary": "jsleak",
        "description": "Scan JS files for secrets, endpoints, and sensitive strings",
        "example": "cat js_urls.txt | jsleak",
    },
    "jsluice": {
        "type": "go",
        "package": "github.com/BishopFox/jsluice/cmd/jsluice@latest",
        "binary": "jsluice",
        "description": "Extract URLs, paths, and secrets from JavaScript at scale",
        "example": "cat js_files.txt | jsluice urls",
    },
    "jsecret": {
        "type": "git",
        "repo": "https://github.com/raoufmaklouf/jsecret.git",
        "path": "/opt/jsecret", "binary": "jsecret",
        "entrypoint": "/opt/jsecret/jsecret.py",
        "requirements": ["-r", "/opt/jsecret/requirements.txt"],
        "description": "Extract API keys and secrets from JavaScript files",
        "example": "jsecret -u https://target.com",
    },
    "secretfinder": {
        "type": "git",
        "repo": "https://github.com/m4ll0k/SecretFinder.git",
        "path": "/opt/SecretFinder", "binary": "secretfinder",
        "entrypoint": "/opt/SecretFinder/SecretFinder.py",
        "requirements": ["-r", "/opt/SecretFinder/requirements.txt"],
        "description": "Regex-based API key and secret scanner in JS and HTML",
        "example": "python3 SecretFinder.py -i https://target.com/main.js -o cli",
    },
    "gitleaks": {
        "type": "go",
        "package": "github.com/gitleaks/gitleaks/v8@latest",
        "binary": "gitleaks",
        "description": "Scan git repos and directories for hardcoded secrets",
        "example": "gitleaks detect --source . -v",
    },
    "trufflehog": {
        "type": "go",
        "package": "github.com/trufflesecurity/trufflehog/v3@latest",
        "binary": "trufflehog",
        "description": "Deep secret scanning across git history, S3, and more",
        "example": "trufflehog git https://github.com/target/repo --only-verified",
    },
    "git-dumper": {
        "type": "python", "package": "git-dumper", "binary": "git-dumper",
        "description": "Dump an exposed .git directory from a web server",
        "example": "git-dumper https://target.com/.git ./output",
    },
    "githound": {
        "type": "git",
        "repo": "https://github.com/tillson/git-hound.git",
        "path": "/opt/git-hound", "binary": "githound",
        "build_cmd": "go build -o githound .",
        "description": "GitHub secrets hunter — scans repos for leaked credentials",
        "example": "githound --org target-org --keywords api_key,secret",
    },
    "gau": {
        "type": "go",
        "package": "github.com/lc/gau/v2/cmd/gau@latest",
        "binary": "gau",
        "description": "Fetch URLs from AlienVault OTX, Wayback Machine, Common Crawl",
        "example": "gau example.com",
    },
    "waybackurls": {
        "type": "go",
        "package": "github.com/tomnomnom/waybackurls@latest",
        "binary": "waybackurls",
        "description": "Fetch all archived URLs from the Wayback Machine",
        "example": "echo example.com | waybackurls",
    },
    "github-dorks": {
        "type": "git",
        "repo": "https://github.com/techgaun/github-dorks.git",
        "path": "/opt/github-dorks", "binary": "github-dorks",
        "entrypoint": "/opt/github-dorks/github-dorks.py",
        "requirements": ["-r", "/opt/github-dorks/requirements.txt"],
        "description": "GitHub dorking to surface sensitive data in public repos",
        "example": "github-dorks -u target-org",
    },
    "virustotalx": {
        "type": "git",
        "repo": "https://github.com/ru3y7/virustotalx.git",
        "path": "/opt/virustotalx", "binary": "virustotalx",
        "entrypoint": "/opt/virustotalx/virustotalx.py",
        "requirements": ["-r", "/opt/virustotalx/requirements.txt"],
        "description": "VirusTotal intelligence for domain, IP, URL, and file analysis",
        "example": "virustotalx -d target.com --api-key VT_KEY",
    },
    "jeeves": {
        "type": "git",
        "repo": "https://github.com/ferreiraklet/Jeeves.git",
        "path": "/opt/jeeves", "binary": "jeeves",
        "entrypoint": "/opt/jeeves/jeeves.py",
        "requirements": ["-r", "/opt/jeeves/requirements.txt"],
        "description": "OSINT automation for passive reconnaissance",
        "example": "python3 jeeves.py -d target.com",
    },
    "xsstrike": {
        "type": "git",
        "repo": "https://github.com/s0md3v/XSStrike.git",
        "path": "/opt/XSStrike", "binary": "xsstrike",
        "entrypoint": "/opt/XSStrike/xsstrike.py",
        "requirements": ["-r", "/opt/XSStrike/requirements.txt"],
        "description": "Advanced XSS detection with DOM analysis and WAF bypass",
        "example": "python3 xsstrike.py -u 'https://target.com/search?q=test'",
    },
    "dalfox": {
        "type": "go",
        "package": "github.com/hahwul/dalfox/v2@latest",
        "binary": "dalfox",
        "description": "Modern XSS scanner and parameter analyzer",
        "example": "dalfox url https://target.com",
    },
    "sqlmap": {
        "type": "git",
        "repo": "https://github.com/sqlmapproject/sqlmap.git",
        "path": "/opt/sqlmap", "binary": "sqlmap",
        "entrypoint": "/opt/sqlmap/sqlmap.py",
        "description": "Automated SQL injection detection and database takeover",
        "example": "sqlmap -u 'https://target.com/search?q=test' --batch --dbs",
    },
    "ghauri": {
        "type": "git",
        "repo": "https://github.com/r0oth3x49/ghauri.git",
        "path": "/opt/ghauri", "binary": "ghauri",
        "entrypoint": "/opt/ghauri/ghauri.py",
        "requirements": ["-r", "/opt/ghauri/requirements.txt"],
        "description": "Advanced SQL injection detection and exploitation",
        "example": "python3 ghauri.py -u https://target.com",
    },
    "dotdotpwn": {
        "type": "git",
        "repo": "https://github.com/wireghoul/dotdotpwn.git",
        "path": "/opt/dotdotpwn", "binary": "dotdotpwn",
        "entrypoint": "/opt/dotdotpwn/dotdotpwn.pl",
        "description": "Directory traversal and path traversal fuzzer",
        "example": "perl dotdotpwn.pl -h https://target.com",
    },
    "graphqlmap": {
        "type": "git",
        "repo": "https://github.com/swisskyrepo/GraphQLmap.git",
        "path": "/opt/GraphQLmap", "binary": "graphqlmap",
        "entrypoint": "/opt/GraphQLmap/graphqlmap.py",
        "requirements": ["-r", "/opt/GraphQLmap/requirements.txt"],
        "description": "GraphQL endpoint enumeration and injection testing",
        "example": "python3 graphqlmap.py -u https://target.com/graphql",
    },
    "nosqlmap": {
        "type": "git",
        "repo": "https://github.com/codingo/NoSQLMap.git",
        "path": "/opt/NoSQLMap", "binary": "nosqlmap",
        "entrypoint": "/opt/NoSQLMap/nosqlmap.py",
        "requirements": ["-r", "/opt/NoSQLMap/requirements.txt"],
        "description": "Automated NoSQL injection for MongoDB, CouchDB, and Redis",
        "example": "python3 nosqlmap.py -u https://target.com",
    },
    "cvinder": {
        "type": "git",
        "repo": "https://github.com/3a7/CVINDER.git",
        "path": "/opt/CVINDER", "binary": "cvinder",
        "entrypoint": "/opt/CVINDER/cvinder.py",
        "requirements": ["-r", "/opt/CVINDER/requirements.txt"],
        "description": "CVE identifier and vulnerability finder",
        "example": "cvinder -d target.com",
    },
    "aidor": {
        "type": "git",
        "repo": "https://github.com/abdulahadtheCyber-pixel/AIDOR.git",
        "path": "/opt/AIDOR", "binary": "aidor",
        "entrypoint": "/opt/AIDOR/aidor.py",
        "requirements": ["-r", "/opt/AIDOR/requirements.txt"],
        "description": "Automated IDOR scanner",
        "example": "aidor -u https://target.com",
    },
    "metasploit-framework": {
        "type": "git",
        "repo": "https://github.com/rapid7/metasploit-framework.git",
        "path": "/opt/metasploit-framework", "binary": "msfconsole",
        "entrypoint": "/opt/metasploit-framework/msfconsole",
        "post_clone": "./msfupdate",
        "description": "Full-featured penetration testing framework",
        "example": "msfconsole",
    },
    "ssrfmap": {
        "type": "git",
        "repo": "https://github.com/swisskyrepo/SSRFmap.git",
        "path": "/opt/SSRFmap", "binary": "ssrfmap",
        "entrypoint": "/opt/SSRFmap/ssrfmap.py",
        "requirements": ["-r", "/opt/SSRFmap/requirements.txt"],
        "description": "Automatic SSRF detection and exploitation",
        "example": "python3 ssrfmap.py -r request.txt -p url",
    },
    "corsy": {
        "type": "git",
        "repo": "https://github.com/s0md3v/Corsy.git",
        "path": "/opt/Corsy", "binary": "corsy",
        "entrypoint": "/opt/Corsy/corsy.py",
        "requirements": ["-r", "/opt/Corsy/requirements.txt"],
        "description": "CORS misconfiguration scanner",
        "example": "python3 corsy.py -u https://target.com",
    },
    "jwt_tool": {
        "type": "git",
        "repo": "https://github.com/ticarpi/jwt_tool.git",
        "path": "/opt/jwt_tool", "binary": "jwt_tool",
        "entrypoint": "/opt/jwt_tool/jwt_tool.py",
        "requirements": ["-r", "/opt/jwt_tool/requirements.txt"],
        "description": "Test, tamper, and crack JWTs for auth bypass vulnerabilities",
        "example": "python3 jwt_tool.py <JWT> -T",
    },
    "cloud_enum": {
        "type": "python", "package": "cloud_enum", "binary": "cloud_enum",
        "description": "Multi-cloud OSINT for AWS, Azure, and GCP public resources",
        "example": "cloud_enum -k target -t aws,azure,gcp",
    },
    "s3scanner": {
        "type": "python", "package": "s3scanner", "binary": "s3scanner",
        "description": "Find and enumerate misconfigured open S3 buckets",
        "example": "s3scanner scan --bucket target-bucket",
    },
    "subjack": {
        "type": "git",
        "repo": "https://github.com/haccer/subjack.git",
        "path": "/opt/subjack", "binary": "subjack",
        "build_cmd": "go build -o subjack .",
        "description": "Subdomain takeover detection across 50+ services",
        "example": "subjack -w subs.txt -t 100 -timeout 30",
    },
    "subzy": {
        "type": "go",
        "package": "github.com/PentestPad/subzy@latest",
        "binary": "subzy",
        "description": "Fast subdomain takeover checker against 100+ signatures",
        "example": "subzy run --targets subs.txt",
    },
    "wpscan": {
        "type": "ruby", "package": "wpscan", "binary": "wpscan",
        "description": "WordPress security scanner — themes, plugins, users, CVEs",
        "example": "wpscan --url https://target.com --enumerate vp,vt,u",
    },
    "droopescan": {
        "type": "python", "package": "droopescan", "binary": "droopescan",
        "description": "CMS scanner for Drupal, SilverStripe, WordPress, and Joomla",
        "example": "droopescan scan drupal -u https://target.com",
    },
    "nikto": {
        "type": "apt", "package": "nikto", "binary": "nikto", "apt": "nikto",
        "description": "Web server misconfiguration and vulnerability scanner",
        "example": "nikto -h https://target.com",
    },
    "wafw00f": {
        "type": "python", "package": "wafw00f", "binary": "wafw00f",
        "description": "WAF detection and fingerprinting — 180+ WAF products",
        "example": "wafw00f https://target.com",
    },
    "graphw00f": {
        "type": "git",
        "repo": "https://github.com/dolevf/graphw00f.git",
        "path": "/opt/graphw00f", "binary": "graphw00f",
        "entrypoint": "/opt/graphw00f/graphw00f",
        "requirements": ["-r", "/opt/graphw00f/requirements.txt"],
        "description": "GraphQL server engine fingerprinting and detection",
        "example": "graphw00f -t https://target.com/graphql",
    },
    "gowitness": {
        "type": "go",
        "package": "github.com/sensepost/gowitness@latest",
        "binary": "gowitness",
        "description": "Web screenshot utility for visual recon at scale",
        "example": "gowitness scan file -f alive.txt --screenshot-path ./screens",
    },
    "hakoriginfinder": {
        "type": "go",
        "package": "github.com/hakluke/hakoriginfinder@latest",
        "binary": "hakoriginfinder",
        "description": "Discover the origin IP behind CDN and WAF providers",
        "example": "echo target.com | hakoriginfinder",
    },
    "pegpon": {
        "type": "git",
        "repo": "https://github.com/LABx-EnV/PEGPON.git",
        "path": "/opt/PEGPON", "binary": "pegpon",
        "entrypoint": "/opt/PEGPON/pegpon",
        "description": "Bash automation for subdomain enumeration and recon",
        "example": "pegpon -d example.com",
    },
    "reconftw": {
        "type": "git",
        "repo": "https://github.com/six2dez/reconftw.git",
        "path": "/opt/reconftw", "binary": "reconftw",
        "entrypoint": "/opt/reconftw/reconftw.sh",
        "post_clone": "./install.sh",
        "description": "Full-cycle recon automation wrapping 35+ tools",
        "example": "./reconftw.sh -d target.com -a",
    },
    "anew": {
        "type": "go",
        "package": "github.com/tomnomnom/anew@latest",
        "binary": "anew",
        "description": "Append new unique lines to a file, de-duplicating on the fly",
        "example": "cat new.txt | anew all.txt",
    },
    "gf": {
        "type": "go",
        "package": "github.com/tomnomnom/gf@latest",
        "binary": "gf",
        "post_install": "git clone --depth 1 https://github.com/1ndianl33t/Gf-Patterns /tmp/gf-patterns && mkdir -p ~/.gf && cp /tmp/gf-patterns/*.json ~/.gf/",
        "description": "Grep wrapper with named pattern sets for bug bounty",
        "example": "cat urls.txt | gf sqli",
    },
    "seclists": {
        "type": "git",
        "repo": "https://github.com/danielmiessler/SecLists.git",
        "path": "/opt/seclists", "binary": "seclists",
        "description": "Curated wordlist collection for all recon phases",
        "example": "ffuf -w /opt/seclists/Discovery/Web-Content/common.txt -u https://target.com/FUZZ",
    },
    "interactsh": {
        "type": "go",
        "package": "github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest",
        "binary": "interactsh-client",
        "description": "Out-of-band interaction client for blind SSRF, XXE, and OOB",
        "example": "interactsh-client -v",
    },
    "uro": {
        "type": "python", "package": "uro", "binary": "uro",
        "description": "Deduplicate and clean URL lists by stripping redundant params",
        "example": "cat urls.txt | uro",
    },
    "notify": {
        "type": "go",
        "package": "github.com/projectdiscovery/notify/cmd/notify@latest",
        "binary": "notify",
        "description": "Real-time alerts to Slack, Discord, or Telegram from any tool",
        "example": "subfinder -d target.com | notify -silent",
    },
    "enumrust": {
        "type": "cargo",
        "repo": "https://github.com/KingOfBugbounty/enumrust.git",
        "path": "/opt/enumrust", "binary": "enumrust",
        "build_cmd": "cargo build --release",
        "description": "Rust-based fast subdomain and host enumeration",
        "example": "./enumrust target.com",
    },
}


def get_tool(name: str) -> Optional[Dict[str, Any]]:
    return TOOL_DEFINITIONS.get(name)


def list_tools() -> list:
    return list(TOOL_DEFINITIONS.keys())
