"""Tool configuration - minimal, validated"""
from typing import Dict, Any, Optional

# Only essential fields required
TOOL_SCHEMA = {
    "type": str,
    "binary": str,
    "description": str,
}

# All 34 recon tools - kept simple
TOOL_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "amass": {
        "type": "go",
        "package": "github.com/owasp-amass/amass/v4/cmd/amass",
        "binary": "amass",
        "apt": "amass",
        "description": "In-depth attack surface mapping with graph visualization",
        "example": "amass enum -d target.com -o subs.txt",
    },
    "subfinder": {
        "type": "go",
        "package": "github.com/projectdiscovery/subfinder/v2/cmd/subfinder",
        "binary": "subfinder",
        "apt": "subfinder",
        "description": "Fast subdomain discovery using 30+ passive sources",
        "example": "subfinder -d target.com -silent -o subs.txt",
    },
    "httpx": {
        "type": "go",
        "package": "github.com/projectdiscovery/httpx/cmd/httpx",
        "binary": "httpx",
        "apt": "httpx",
        "description": "HTTP toolkit for probing, fingerprinting, and crawling",
        "example": "cat subs.txt | httpx -silent -status-code",
    },
    "dnsx": {
        "type": "go",
        "package": "github.com/projectdiscovery/dnsx/cmd/dnsx",
        "binary": "dnsx",
        "apt": "dnsx",
        "go_version": "1.24.0",
        "description": "Multi-purpose DNS toolkit for enumeration and resolution",
        "example": "cat subs.txt | dnsx -a -resp -silent",
    },
    "nuclei": {
        "type": "go",
        "package": "github.com/projectdiscovery/nuclei/v3/cmd/nuclei",
        "binary": "nuclei",
        "apt": "nuclei",
        "go_version": "1.22.0",
        "description": "Fast vulnerability scanner with 10,000+ community templates",
        "post_install": "nuclei -ut -silent",
        "example": "cat alive.txt | nuclei -t exposures/ -severity critical,high",
    },
    "katana": {
        "type": "go",
        "package": "github.com/projectdiscovery/katana/cmd/katana",
        "binary": "katana",
        "apt": "katana",
        "go_version": "1.24.1",
        "description": "Next-gen crawling and spidering framework",
        "example": "katana -u https://target.com -silent -depth 3 -js-crawl",
    },
    "ffuf": {
        "type": "go",
        "package": "github.com/ffuf/ffuf/v2",
        "binary": "ffuf",
        "apt": "ffuf",
        "description": "Fast web fuzzer for directory brute-forcing",
        "example": "ffuf -w wordlist.txt -u https://target.com/FUZZ",
    },
    "gospider": {
        "type": "go",
        "package": "github.com/jaeles-project/gospider",
        "binary": "gospider",
        "apt": None,
        "description": "Fast web spider for endpoint discovery",
        "example": "gospider -s https://target.com -o output",
    },
    "assetfinder": {
        "type": "go",
        "package": "github.com/tomnomnom/assetfinder",
        "binary": "assetfinder",
        "apt": None,
        "description": "Find subdomains from Certificate Transparency logs",
        "example": "assetfinder --subs-only target.com",
    },
    "shuffledns": {
        "type": "go",
        "package": "github.com/projectdiscovery/shuffledns/cmd/shuffledns",
        "binary": "shuffledns",
        "apt": "shuffledns",
        "description": "MassDNS wrapper for subdomain brute-forcing",
        "example": "shuffledns -list subs.txt -d target.com -r resolvers.txt",
    },
    "naabu": {
        "type": "go",
        "package": "github.com/projectdiscovery/naabu/v2/cmd/naabu",
        "binary": "naabu",
        "apt": "naabu",
        "description": "Fast port scanner for network reconnaissance",
        "example": "naabu -host target.com -p 80,443,8080,8443",
    },
    "metabigor": {
        "type": "go",
        "package": "github.com/j3ssie/metabigor",
        "binary": "metabigor",
        "apt": None,
        "description": "Network intelligence for ASN and IP range discovery",
        "example": "metabigor net -d target.com",
    },
    "sublist3r": {
        "type": "python",
        "package": "sublist3r==1.0",
        "binary": "sublist3r",
        "apt": None,
        "description": "Fast subdomain enumeration using OSINT sources",
        "example": "sublist3r -d target.com -o subs.txt",
    },
    "cewl": {
        "type": "apt",
        "package": "cewl",
        "binary": "cewl",
        "apt": "cewl",
        "description": "Custom wordlist generator from website spidering",
        "example": "cewl -d 2 -m 8 -w custom.txt https://target.com",
    },
    "subdomainizer": {
        "type": "git",
        "repo": "https://github.com/nsonaniya2010/SubDomainizer.git",
        "path": "/opt/SubDomainizer",
        "binary": "subdomainizer",
        "entrypoint": "/opt/SubDomainizer/SubDomainizer.py",
        "requirements": ["-r", "/opt/SubDomainizer/requirements.txt"],
        "description": "Find interesting subdomains and secrets in external resources",
        "example": "subdomainizer -u https://target.com -o results.txt",
    },
    "linkfinder": {
        "type": "git",
        "repo": "https://github.com/GerbenJavado/LinkFinder.git",
        "path": "/opt/LinkFinder",
        "binary": "linkfinder",
        "entrypoint": "/opt/LinkFinder/linkfinder.py",
        "requirements": ["-r", "/opt/LinkFinder/requirements.txt"],
        "post_clone": "npm install --silent",
        "description": "Discover hidden endpoints in JavaScript files",
        "example": "linkfinder -i https://target.com/main.js -o cli",
    },
    "cloud_enum": {
        "type": "python",
        "package": "cloud_enum",
        "binary": "cloud_enum",
        "apt": None,
        "description": "Multi-cloud OSINT for AWS/Azure/GCP public resources",
        "example": "cloud_enum -k target -t aws,azure,gcp",
    },
    "githound": {
        "type": "git",
        "repo": "https://github.com/tillson/git-hound.git",
        "path": "/opt/git-hound",
        "binary": "githound",
        "build_cmd": "go build -o githound .",
        "description": "GitHub secrets hunter and sensitive data finder",
        "example": "githound --org target-org --keywords api_key,password",
    },
    "virustotalx": {
        "type": "git",
        "repo": "https://github.com/ru3y7/virustotalx.git",
        "path": "/opt/virustotalx",
        "binary": "virustotalx",
        "entrypoint": "/opt/virustotalx/virustotalx.py",
        "requirements": ["-r", "/opt/virustotalx/requirements.txt"],
        "description": "VirusTotal intelligence tool for domain/IP/URL analysis",
        "example": "virustotalx -d target.com --api-key YOUR_VT_KEY",
    },
    "github-subdomains": {
        "type": "go",
        "package": "github.com/gwen001/github-subdomains",
        "binary": "github-subdomains",
        "apt": None,
        "description": "Find subdomains from GitHub commits and repos",
        "example": "github-subdomains -d target.com -t github_token",
    },
    "arjun": {
        "type": "go",
        "package": "github.com/s0md3v/Arjun/cmd/arjun",
        "binary": "arjun",
        "apt": None,
        "description": "HTTP parameter discovery suite",
        "example": "arjun -u https://target.com",
    },
    "paramspider": {
        "type": "git",
        "repo": "https://github.com/devanshbatham/ParamSpider.git",
        "path": "/opt/ParamSpider",
        "binary": "paramspider",
        "entrypoint": "/opt/ParamSpider/paramspider.py",
        "requirements": ["-r", "/opt/ParamSpider/requirements.txt"],
        "description": "Mine parameters from web archives",
        "example": "paramspider -d target.com",
    },
    "xsstrike": {
        "type": "git",
        "repo": "https://github.com/s0md3v/XSStrike.git",
        "path": "/opt/XSStrike",
        "binary": "xsstrike",
        "entrypoint": "/opt/XSStrike/xsstrike.py",
        "requirements": ["-r", "/opt/XSStrike/requirements.txt"],
        "description": "Advanced XSS detection suite",
        "example": "xsstrike -u https://target.com/search?q=test",
    },
    "dalfox": {
        "type": "go",
        "package": "github.com/dalfox/dalfox/v2",
        "binary": "dalfox",
        "apt": None,
        "description": "Modern XSS scanner and parameter analyzer",
        "example": "dalfox url https://target.com",
    },
    "github-dorks": {
        "type": "git",
        "repo": "https://github.com/techgaun/github-dorks.git",
        "path": "/opt/github-dorks",
        "binary": "github-dorks",
        "entrypoint": "/opt/github-dorks/github-dorks.py",
        "requirements": ["-r", "/opt/github-dorks/requirements.txt"],
        "description": "GitHub dorking for sensitive data exposure",
        "example": "github-dorks -u target-org",
    },
    "jsecret": {
        "type": "git",
        "repo": "https://github.com/raoufmaklouf/jsecret.git",
        "path": "/opt/jsecret",
        "binary": "jsecret",
        "entrypoint": "/opt/jsecret/jsecret.py",
        "requirements": ["-r", "/opt/jsecret/requirements.txt"],
        "description": "JavaScript secret and API key finder",
        "example": "jsecret -u https://target.com",
    },
    "waybackurls": {
        "type": "go",
        "package": "github.com/tomnomnom/waybackurls",
        "binary": "waybackurls",
        "apt": None,
        "description": "Fetch URLs from Wayback Machine and Common Crawl",
        "example": "echo target.com | waybackurls",
    },
    "gau": {
        "type": "go",
        "package": "github.com/lc/gau/v2/cmd/gau",
        "binary": "gau",
        "apt": None,
        "description": "GetAllUrls - URL enumerator from multiple sources",
        "example": "gau target.com",
    },
    "anew": {
        "type": "go",
        "package": "github.com/tomnomnom/anew",
        "binary": "anew",
        "apt": None,
        "description": "Append new lines to files, useful for collecting output",
        "example": "cat new-subs.txt | anew all-subs.txt",
    },
    "interactsh": {
        "type": "go",
        "package": "github.com/projectdiscovery/interactsh/cmd/interactsh-client",
        "binary": "interactsh-client",
        "apt": None,
        "description": "Out-of-band interaction client for blind testing",
        "example": "interactsh-client",
    },
    "sqlmap": {
        "type": "git",
        "repo": "https://github.com/sqlmapproject/sqlmap.git",
        "path": "/opt/sqlmap",
        "binary": "sqlmap",
        "entrypoint": "/opt/sqlmap/sqlmap.py",
        "description": "Automatic SQL injection and database takeover tool",
        "example": "sqlmap -u https://target.com/search?q=test --batch",
    },
    "aidor": {
        "type": "git",
        "repo": "https://github.com/abdulahadtheCyber-pixel/AIDOR.git",
        "path": "/opt/AIDOR",
        "binary": "aidor",
        "entrypoint": "/opt/AIDOR/aidor.py",
        "requirements": ["-r", "/opt/AIDOR/requirements.txt"],
        "description": "Automated Insecure Direct Object Reference scanner",
        "example": "aidor -u https://target.com",
    },
    "cvinder": {
        "type": "git",
        "repo": "https://github.com/3a7/CVINDER.git",
        "path": "/opt/CVINDER",
        "binary": "cvinder",
        "entrypoint": "/opt/CVINDER/cvinder.py",
        "requirements": ["-r", "/opt/CVINDER/requirements.txt"],
        "description": "CVE identifier and vulnerability finder",
        "example": "cvinder -d target.com",
    },
    # ── Additional Tools (30 more to reach 63) ──
    "bbot": {
        "type": "python",
        "package": "bbot",
        "binary": "bbot",
        "apt": None,
        "description": "Recursive internet scanner",
        "example": "bbot target.com",
    },
    "masscan": {
        "type": "git",
        "repo": "https://github.com/robertdavidgraham/masscan.git",
        "path": "/opt/masscan",
        "binary": "masscan",
        "build_cmd": "make && sudo make install",
        "description": "High-speed port scanner",
        "example": "masscan -p1-65535 target.com",
    },
    "wafw00f": {
        "type": "git",
        "repo": "https://github.com/EnableSecurity/wafw00f.git",
        "path": "/opt/wafw00f",
        "binary": "wafw00f",
        "entrypoint": "/opt/wafw00f/wafw00f",
        "requirements": ["-r", "/opt/wafw00f/requirements.txt"],
        "description": "WAF detection and identification",
        "example": "wafw00f https://target.com",
    },
    "graphw00f": {
        "type": "git",
        "repo": "https://github.com/dolevf/graphw00f.git",
        "path": "/opt/graphw00f",
        "binary": "graphw00f",
        "entrypoint": "/opt/graphw00f/graphw00f",
        "requirements": ["-r", "/opt/graphw00f/requirements.txt"],
        "description": "GraphQL fingerprinting",
        "example": "graphw00f https://target.com/graphql",
    },
    "jsfinder": {
        "type": "git",
        "repo": "https://github.com/0x240x23elu/jsfinder.git",
        "path": "/opt/jsfinder",
        "binary": "jsfinder",
        "entrypoint": "/opt/jsfinder/JSFinder.py",
        "requirements": ["-r", "/opt/jsfinder/requirements.txt"],
        "description": "JavaScript secrets finder",
        "example": "python3 JSFinder.py -u https://target.com",
    },
    "jsluice": {
        "type": "go",
        "package": "github.com/BishopFox/jsluice/cmd/jsluice",
        "binary": "jsluice",
        "apt": None,
        "description": "JavaScript link extractor",
        "example": "cat urls.txt | jsluice",
    },
    "jsleak": {
        "type": "git",
        "repo": "https://github.com/003random/jsleak.git",
        "path": "/opt/jsleak",
        "binary": "jsleak",
        "entrypoint": "/opt/jsleak/jsleak.py",
        "requirements": ["-r", "/opt/jsleak/requirements.txt"],
        "description": "JavaScript leak scanner",
        "example": "python3 jsleak.py -u https://target.com",
    },
    "dirsearch": {
        "type": "git",
        "repo": "https://github.com/maurosoria/dirsearch.git",
        "path": "/opt/dirsearch",
        "binary": "dirsearch",
        "entrypoint": "/opt/dirsearch/dirsearch.py",
        "requirements": ["-r", "/opt/dirsearch/requirements.txt"],
        "description": "Directory brute-forcing",
        "example": "python3 dirsearch.py -u https://target.com",
    },
    "kiterunner": {
        "type": "git",
        "repo": "https://github.com/assetnote/kiterunner.git",
        "path": "/opt/kiterunner",
        "binary": "kr",
        "build_cmd": "go build -o kr ./cmd/kr",
        "description": "Content discovery framework",
        "example": "kr scan https://target.com",
    },
    "xspear": {
        "type": "ruby",
        "package": "XSpear",
        "binary": "xspear",
        "apt": None,
        "description": "XSS scanner with Selenium",
        "example": "xspear -u https://target.com",
    },
    "nikto": {
        "type": "apt",
        "package": "nikto",
        "binary": "nikto",
        "apt": "nikto",
        "description": "Web server scanner",
        "example": "nikto -h https://target.com",
    },
    "metasploit-framework": {
        "type": "git",
        "repo": "https://github.com/rapid7/metasploit-framework.git",
        "path": "/opt/metasploit-framework",
        "binary": "msfconsole",
        "entrypoint": "/opt/metasploit-framework/msfconsole",
        "post_clone": "./msfupdate",
        "description": "Complete penetration testing framework",
        "example": "msfconsole",
    },
    "ghauri": {
        "type": "git",
        "repo": "https://github.com/r0oth3x49/ghauri.git",
        "path": "/opt/ghauri",
        "binary": "ghauri",
        "entrypoint": "/opt/ghauri/ghauri.py",
        "requirements": ["-r", "/opt/ghauri/requirements.txt"],
        "description": "SQL injection scanner",
        "example": "python3 ghauri.py -u https://target.com",
    },
    "nosqlmap": {
        "type": "git",
        "repo": "https://github.com/codingo/NoSQLMap.git",
        "path": "/opt/NoSQLMap",
        "binary": "nosqlmap",
        "entrypoint": "/opt/NoSQLMap/nosqlmap.py",
        "requirements": ["-r", "/opt/NoSQLMap/requirements.txt"],
        "description": "NoSQL database injection",
        "example": "python3 nosqlmap.py -u https://target.com",
    },
    "graphqlmap": {
        "type": "git",
        "repo": "https://github.com/swisskyrepo/GraphQLmap.git",
        "path": "/opt/GraphQLmap",
        "binary": "graphqlmap",
        "entrypoint": "/opt/GraphQLmap/graphqlmap.py",
        "requirements": ["-r", "/opt/GraphQLmap/requirements.txt"],
        "description": "GraphQL security testing",
        "example": "python3 graphqlmap.py -u https://target.com/graphql",
    },
    "dotdotpwn": {
        "type": "git",
        "repo": "https://github.com/wireghoul/dotdotpwn.git",
        "path": "/opt/dotdotpwn",
        "binary": "dotdotpwn",
        "entrypoint": "/opt/dotdotpwn/dotdotpwn.pl",
        "description": "Path traversal fuzzer",
        "example": "perl dotdotpwn.pl -h https://target.com",
    },
    "s3scanner": {
        "type": "git",
        "repo": "https://github.com/sa7mon/S3Scanner.git",
        "path": "/opt/S3Scanner",
        "binary": "s3scanner",
        "entrypoint": "/opt/S3Scanner/s3scanner.py",
        "requirements": ["-r", "/opt/S3Scanner/requirements.txt"],
        "description": "AWS S3 bucket scanner",
        "example": "python3 s3scanner.py buckets.txt",
    },
    "wpscan": {
        "type": "ruby",
        "package": "wpscan",
        "binary": "wpscan",
        "apt": None,
        "description": "WordPress security scanner",
        "example": "wpscan --url https://target.com",
    },
    "droopescan": {
        "type": "git",
        "repo": "https://github.com/droope/droopescan.git",
        "path": "/opt/droopescan",
        "binary": "droopescan",
        "entrypoint": "/opt/droopescan/droopescan.py",
        "requirements": ["-r", "/opt/droopescan/requirements.txt"],
        "description": "CMS scanner (Drupal, Joomla, etc.)",
        "example": "python3 droopescan scan https://target.com",
    },
    "subjack": {
        "type": "git",
        "repo": "https://github.com/haccer/subjack.git",
        "path": "/opt/subjack",
        "binary": "subjack",
        "build_cmd": "go build -o subjack .",
        "description": "Subdomain takeover detection",
        "example": "subjack -w subs.txt -t 50",
    },
    "subzy": {
        "type": "go",
        "package": "github.com/LukaSikic/subzy/cmd/subzy",
        "binary": "subzy",
        "apt": None,
        "description": "Fast subdomain takeover scanner",
        "example": "subzy -target https://target.com",
    },
    "subover": {
        "type": "git",
        "repo": "https://github.com/Ice3man543/SubOver.git",
        "path": "/opt/SubOver",
        "binary": "subover",
        "entrypoint": "/opt/SubOver/subover.py",
        "requirements": ["-r", "/opt/SubOver/requirements.txt"],
        "description": "Subdomain takeover tool",
        "example": "python3 subover.py -l subs.txt",
    },
    "gf": {
        "type": "go",
        "package": "github.com/tomnomnom/gf",
        "binary": "gf",
        "apt": None,
        "description": "Pattern finder for grep",
        "example": "cat response.txt | gf s3",
    },
    "uro": {
        "type": "go",
        "package": "github.com/s0md3v/uro",
        "binary": "uro",
        "apt": None,
        "description": "URL recon tool",
        "example": "uro -u https://target.com",
    },
    "seclists": {
        "type": "git",
        "repo": "https://github.com/danielmiessler/SecLists.git",
        "path": "/usr/share/SecLists",
        "binary": "seclists",
        "description": "Collection of multiple types of lists",
        "example": "ls /usr/share/SecLists/Discovery/Web-Content/common.txt",
    },
    "reconftw": {
        "type": "git",
        "repo": "https://github.com/six2dez/reconftw.git",
        "path": "/opt/reconftw",
        "binary": "reconftw",
        "entrypoint": "/opt/reconftw/reconftw.sh",
        "post_clone": "./install.sh",
        "description": "Automated recon framework",
        "example": "./reconftw.sh -d target.com",
    },
    "enumrust": {
        "type": "git",
        "repo": "https://github.com/KingOfBugbounty/enumrust.git",
        "path": "/opt/enumrust",
        "binary": "enumrust",
        "build_cmd": "cargo build --release",
        "description": "Rust-based enumeration tool",
        "example": "./enumrust target.com",
    },
}

def get_tool(name: str) -> Optional[Dict[str, Any]]:
    """Get tool config by name"""
    return TOOL_DEFINITIONS.get(name)

def list_tools() -> list:
    """List all tool names"""
    return list(TOOL_DEFINITIONS.keys())